FROM golang:1.3-cross

RUN go get github.com/tools/godep
RUN go get github.com/aktau/github-release
RUN go get github.com/mitchellh/gox

RUN gox -build-toolchain

ADD . /go/src/github.com/ehazlett/certm

RUN (git clone https://github.com/sstephenson/bats.git && \
    cd bats && ./install.sh /usr/local)

ADD https://get.docker.com/builds/Linux/x86_64/docker-1.5.0 /usr/local/bin/docker

RUN chmod +x /usr/local/bin/docker

ENV SHELL /bin/bash

WORKDIR /go/src/github.com/ehazlett/certm
