#!/bin/bash
set -e
if [ -z "$1" ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

VERSION=$1

if [ -z "$GITHUB_TOKEN" ]; then
    echo "GITHUB_TOKEN must be set for github-release"
    exit 1
fi

echo "Building"
script/build $VERSION

echo "Pushing to Hub"
docker tag -f ehazlett/certm:$VERSION ehazlett/certm:latest
docker push ehazlett/certm:$VERSION
docker push ehazlett/certm:latest

echo "Generating sums"
docker run --rm -v `pwd`:/go/src/github.com/ehazlett/certm certm-build ./script/generate-sums

echo "Creating Tag"
git tag $VERSION
echo "Pushing tag"
git push --tags

echo "Creating Release"
docker run --rm -e GITHUB_TOKEN certm-build github-release release \
    --user ehazlett \
    --repo certm \
    --tag $VERSION \
    --name $VERSION \
    --description "" \
    --pre-release

for BINARY in certm_*; do
    echo "Uploading $BINARY"
    docker run --rm -e GITHUB_TOKEN -v `pwd`:/go/src/github.com/ehazlett/certm \
        certm-build github-release upload \
        --user ehazlett \
        --repo certm \
        --tag $VERSION \
        --name $BINARY \
        --file $BINARY
done
