#!/bin/bash
set -e

docker build -t cert-tool-build -f Dockerfile.build .

docker run --rm -v $(pwd):/go/src/github.com/ehazlett/cert-tool -w /go/src/github.com/ehazlett/cert-tool cert-tool-build make test
